### ISSUE TITLE
Differential expression error

### ISSUE THREAD

**Issue by Tetrajf** [adamd3/BactSeq#2]
Dear Adam

I'm hoping you can perhaps help with the following error.  I ran the pipeline without setting a contrast file previously. Worked perfectly. Now I'm trying to repeat with the contrast file. It's a simple two condition experiment. I have attached the command.err file for the step as well as the sample sheet, contrasts file and my stdout file

Running on a HPC with Ubuntu 20 installed.
The command I ran was within a slurm launcher. I've had to pull the github repository in a rather unusual way. The command after exporting singularity temp paths is:

nextflow run https://github.com/adamd3/BactSeq -latest -r main --paired --data_dir /scratch/sysuser/jonathan/ops/MRC/DE_RNA --sample_file /scratch/sysuser/jonathan/ops/MRC/DE_RNA/samplesheet.txt --ref_genome /scratch/sysuser/jonathan/ops/MRC/DE_RNA/GCF_000195955.2_ASM19595v2_genomic.fna --ref_ann /scratch/sysuser/jonathan/ops/MRC/DE_RNA/genomic.gff --cont_tabl contrasts.tsv -profile singularity

I recognize the group_INF_vs_EFF as a DESEQ2 parameter but I don't know what causes the error or what mistake I may have made.

Kind regards,
Jonathan
[stdout.txt](https://github.com/adamd3/BactSeq/files/14051434/stdout.txt)
[command.txt](https://github.com/adamd3/BactSeq/files/14051435/command.txt)
[samplesheet.txt](https://github.com/adamd3/BactSeq/files/14051436/samplesheet.txt)
[contrasts.txt](https://github.com/adamd3/BactSeq/files/14051437/contrasts.txt)

**Comment by adamd3** [comment]
Hey Jonathan,

I have had a look at your input files and I think I have found the reason for this error. It's basically an unusual case the 'INF' group is being treated as a numeric value (it's read as 'Infinite') instead of a string. This causes a problem for DESeq2.

It should now be fixed, if you could please try again.

Best,
Adam

**Comment by Tetrajf** [comment]
Bwhahahha. Just my luck I use a prohibited word. Thank you so much! It worked now. Thank you!
